name: my-app
region: nyc
services:
  - name: web-service
    git:
      repo_clone_url: https://github.com/user/repo-name.git
      branch: main
    github:
      repo: user/repo-name
      branch: main
      deploy_on_push: true
    image:
      registry_type: DOCR
      registry: ghcr.io
      repository: user/repo-name
      tag: latest
      digest: sha256:1234567890abcdef
      registry_credentials: "$your_username:$access_token"
      deploy_on_push:
        enabled: true
    gitlab:
      repo: user/repo-name
      branch: main
      deploy_on_push: true
    dockerfile_path: ./Dockerfile
    build_command: npm install && npm run build
    run_command: npm start
    source_dir: ./web
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
        type: general
      - key: SECRET_KEY
        value: EV[1:zqiRIeaaYK/NqctZDYzy6t0pTrtRDeq8:wqGpZRrsKN5nPhWQrS479cfBiXT0WQ==]
        type: secret
    instance_count: 2
    autoscaling:
      min_instances: 1
      max_instances: 5
      metrics:
        cpu:
          percent: 75
    http_port: 8080
    health_check:
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 2
      failure_threshold: 3
      http_path: /api
      port: 8080
    liveness_health_check:
     initial_delay_seconds: 5
     period_seconds: 10
     timeout_seconds: 5
     success_threshold: 2
     failure_threshold: 3
     http_path: /api
     port: 8080
    internal_ports: [8080, 80]
    alerts:
      - rule: CPU_UTILIZATION
        disabled: false
        operator: GREATER_THAN
        value: 75
        window: FIVE_MINUTES
    log_destinations:
      - name: example-logger
        papertrail:
          endpoint: logs.papertrailapp.com:12345
        datadog:
          endpoint: logs.datadoghq.com:12345
          api_key: 82d168fdae72372ec79408dd22912d97
        logtail:
          token: 123e4567-e89b-12d3-a456-426614174000
        open_search:
          endpoint: logs.example.com:12345
          basic_auth:
            user: doadmin
            password: 1234567890abcdef
          index_name: example-index
          cluster_name: example-cluster
    termination:
      drain_seconds: 30
      grace_period_seconds: 90
static_sites:
  - name: static-site
    git:
      repo_clone_url: https://github.com/user/repo-name.git
      branch: main
    github:
      repo: user/repo-name
      branch: main
      deploy_on_push: true
    gitlab:
      repo: user/repo-name
      branch: main
      deploy_on_push: true
    dockerfile_path: ./Dockerfile
    build_command: npm install && npm run build
    source_dir: ./web
    output_dir: build
    index_document: index.html
    error_document: 404.html
    envs:
      - key: API_ENDPOINT
        value: https://api.example.com
        scope: RUN_TIME
        type: general
      - key: SECRET_KEY
        value: EV[1:zqiRIeaaYK/NqctZDYzy6t0pTrtRDeq8:wqGpZRrsKN5nPhWQrS479cfBiXT0WQ==]
        type: secret
    catchall_document: index.html
workers:
  - name: background-worker
    git:
      repo_clone_url: https://github.com/user/repo-name.git
      branch: main
    github:
      repo: user/repo-name
      branch: main
      deploy_on_push: true
    image:
      registry_type: DOCR
      registry: ghcr.io
      repository: user/repo-name
      tag: latest
      digest: sha256:1234567890abcdef
      registry_credentials: "$your_username:$access_token"
      deploy_on_push:
        enabled: true
    gitlab:
      repo: user/repo-name
      branch: main
      deploy_on_push: true
    dockerfile_path: ./Dockerfile
    build_command: npm install && npm run build
    run_command: npm start
    source_dir: ./web
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
        type: general
      - key: SECRET_KEY
        value: EV[1:zqiRIeaaYK/NqctZDYzy6t0pTrtRDeq8:wqGpZRrsKN5nPhWQrS479cfBiXT0WQ==]
        type: secret
    instance_count: 2
    autoscaling:
      min_instances: 1
      max_instances: 5
      metrics:
        cpu:
          percent: 75
    alerts:
      - rule: CPU_UTILIZATION
        disabled: false
        operator: GREATER_THAN
        value: 75
        window: FIVE_MINUTES
    log_destinations:
      - name: example-logger
        papertrail:
          endpoint: logs.papertrailapp.com:12345
        datadog:
          endpoint: logs.datadoghq.com:12345
          api_key: 82d168fdae72372ec79408dd22912d97
        logtail:
          token: 123e4567-e89b-12d3-a456-426614174000
        open_search:
          endpoint: logs.example.com:12345
          basic_auth:
            user: doadmin
            password: 1234567890abcdef
          index_name: example-index
          cluster_name: example-cluster
    termination:
      drain_seconds: 30
      grace_period_seconds: 90
jobs:
    git:
      repo_clone_url: https://github.com/user/repo-name.git
      branch: main
    github:
      repo: user/repo-name
      branch: main
      deploy_on_push: true
    image:
      registry_type: DOCR
      registry: ghcr.io
      repository: user/repo-name
      tag: latest
      digest: sha256:1234567890abcdef
      registry_credentials: "$your_username:$access_token"
      deploy_on_push:
        enabled: true
    gitlab:
      repo: user/repo-name
      branch: main
      deploy_on_push: true
    dockerfile_path: ./Dockerfile
    build_command: npm install && npm run build
    run_command: npm start
    source_dir: ./web
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
        type: general
      - key: SECRET_KEY
        value: EV[1:zqiRIeaaYK/NqctZDYzy6t0pTrtRDeq8:wqGpZRrsKN5nPhWQrS479cfBiXT0WQ==]
        type: secret
    instance_count: 2
    kind: SCHEDULED
    schedule:
      cron: "*/15 * * * *"
      time_zone: Asia/Kolkata
    alerts:
      - rule: CPU_UTILIZATION
        disabled: false
        operator: GREATER_THAN
        value: 75
        window: FIVE_MINUTES
    log_destinations:
      - name: example-logger
        papertrail:
          endpoint: logs.papertrailapp.com:12345
        datadog:
          endpoint: logs.datadoghq.com:12345
          api_key: 82d168fdae72372ec79408dd22912d97
        logtail:
          token:  123e4567-e89b-12d3-a456-426614174000
        open_search:
          endpoint: logs.example.com:12345
          basic_auth:
            user: doadmin
            password: 1234567890abcdef
          index_name: example-index
          cluster_name: example-cluster
    termination:
      drain_seconds: 30
      grace_period_seconds: 90
functions:
  - name: example-function
    git:
      repo_clone_url: https://github.com/user/repo-name.git
      branch: main
    github:
      repo: user/repo-name
      branch: main
      deploy_on_push: true
    gitlab:
      repo: user/repo-name
      branch: main
      deploy_on_push: true
    source_dir: ./web
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
        type: general
      - key: SECRET_KEY
        value: EV[1:zqiRIeaaYK/NqctZDYzy6t0pTrtRDeq8:wqGpZRrsKN5nPhWQrS479cfBiXT0WQ==]
        type: secret
    alerts:
      - rule: CPU_UTILIZATION
        disabled: false
        operator: GREATER_THAN
        value: 75
        window: FIVE_MINUTES
    log_destinations:
      - name: example-logger
        papertrail:
          endpoint: logs.papertrailapp.com:12345
        datadog:
          endpoint: logs.datadoghq.com:12345
          api_key: 82d168fdae72372ec79408dd22912d97
        logtail:
          token: 123e4567-e89b-12d3-a456-426614174000
        open_search:
          endpoint: logs.example.com:12345
          basic_auth:
            user: doadmin
            password: 1234567890abcdef
          index_name: example-index
          cluster_name: example-cluster
    termination:
      drain_seconds: 30
      grace_period_seconds: 90
databases:
  - name: postgres-db
    engine: PG
    version: "13"
    production: true
    cluster_name: example-cluster
    db_name: example-db
    db_user: example-user
domains:
  - domain: app.example.com
    type: primary
    wildcard: true
    zone: example.com
    minimum_tls_version: 1.2
envs:
  - key: NODE_ENV
    value: production
    scope: RUN_TIME
    type: general
  - key: SECRET_KEY
    value: EV[1:zqiRIeaaYK/NqctZDYzy6t0pTrtRDeq8:wqGpZRrsKN5nPhWQrS479cfBiXT0WQ==]
    type: secret
alerts:
  - rule: CPU_UTILIZATION
    disabled: false
    operator: GREATER_THAN
    value: 75
    window: FIVE_MINUTES
ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: web-service
        preserve_path_prefix: true
        rewrite: /api
      redirect:
        uri: /developers
        authority: example.com
        port: 8080
        scheme: https
        redirect_code: 302
      cors:
        allow_origins:
          - exact: https://example.com
            regex: ^https://.*\.example\.com$
        allow_methods: ["GET", "POST"]
        allow_headers: ["Authorization"]
        expose_headers: ["Authorization"]
        max_age: 5h30m
        allow_credentials: true
maintenance:
  enabled: false
disable_edge_cache: false
disable_email_obfuscation: false
enhanced_threat_control_enabled: false
vpc:
  id: 5218b393-8cef-41a3-a436-72a20de7cba4
