"""major state update

Revision ID: 7da67e5f4972
Revises: e66ff071b846
Create Date: 2026-01-21 01:49:25.146047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7da67e5f4972'
down_revision: Union[str, Sequence[str], None] = 'e66ff071b846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa_enum = sa.Enum(
        'tools_selection',
        'env_vars_setup',
        'auth_selection',
        'code_gen',
        'deployment_selection',
        'ready',
        name='mcpserversetupstatus',
    )
    sa_enum.create(op.get_bind(), checkfirst=False)
    op.create_table('mcp_environment_variables',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_environment_variables_server_id'), 'mcp_environment_variables', ['server_id'], unique=False)
    op.drop_index(op.f('ix_chat_sessions_server_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.add_column('apikey', sa.Column('server_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_apikey_customer_id'), table_name='apikey')
    op.create_index(op.f('ix_apikey_server_id'), 'apikey', ['server_id'], unique=True)
    op.drop_constraint(op.f('apikey_customer_id_fkey'), 'apikey', type_='foreignkey')
    op.create_foreign_key(None, 'apikey', 'mcp_servers', ['server_id'], ['id'], ondelete='CASCADE')
    op.drop_column('apikey', 'customer_id')
    op.add_column('mcp_servers', sa.Column('setup_status', sa.Enum('tools_selection', 'env_vars_setup', 'auth_selection', 'code_gen', 'deployment_selection', 'ready', name='mcpserversetupstatus'), server_default='tools_selection', nullable=False))
    op.drop_column('mcp_servers', 'status')
    op.drop_column('mcp_tools', 'validation_errors')
    op.drop_column('mcp_tools', 'is_validated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_tools', sa.Column('is_validated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mcp_tools', sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mcp_servers', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('mcp_servers', 'setup_status')
    op.add_column('apikey', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'apikey', type_='foreignkey')
    op.create_foreign_key(op.f('apikey_customer_id_fkey'), 'apikey', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_apikey_server_id'), table_name='apikey')
    op.create_index(op.f('ix_apikey_customer_id'), 'apikey', ['customer_id'], unique=False)
    op.drop_column('apikey', 'server_id')
    op.create_table('chat_sessions',
    sa.Column('server_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], name=op.f('chat_sessions_server_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_sessions_pkey'))
    )
    op.create_index(op.f('ix_chat_sessions_server_id'), 'chat_sessions', ['server_id'], unique=False)
    op.drop_index(op.f('ix_mcp_environment_variables_server_id'), table_name='mcp_environment_variables')
    op.drop_table('mcp_environment_variables')
    # ### end Alembic commands ###
