""" rename apikey table to api_keys

Revision ID: f2feae715014
Revises: a3c8f5e7b123
Create Date: 2026-01-21 20:30:45.699701

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2feae715014"
down_revision: Union[str, Sequence[str], None] = "a3c8f5e7b123"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("apikey", "api_keys")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("api_keys", "apikey")
    # ### end Alembic commands ###
